baseurl = "https://ajaya.me/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "orange"
  showMenuItems = 5
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "Dev / Architect"
    subtitle = "my website"
    keywords = "dev, architect, my website, portfolio, resume"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "4 J 4 Y K"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "git"
        name = "Git"
        url = "https://github.com/4j4yk"
      [[languages.en.menu.main]]
        identifier = "linkedin"
        name = "Linkedin"
        url = "https://www.linkedin.com/in/akhampariya/"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
